### PR TITLE
☄️ add: useCopyToClipboard hook 

### PR DESCRIPTION
**Pull request by mutasim77**
Hey again, I tried to add that hook to the documentation as well, but I encountered some issues. Could you please take a look at the screenshots below?

not importing from prismane:
Screenshot 2023-09-25 at 8 54 20 AM

here's how it looks: 
Screenshot 2023-09-25 at 8 54 32 AM

### CODE REVIEW

**Comment by spleafy** [comment]
Yes, I am sorry, the issue is that the new hook has not been added to the
latest version of Prismane. This is my bad. I am just about to release the
new minor version that includes your hook. Will update when it is released.
Then you will just have to bump the version of prismane up and everything
should work.

**Comment by spleafy** [comment]
It looks great! Thank you very much for the effort put in! I have just released the new minor version of Prismane that includes your hook! I will merge this PR now and bump the version of Prismane in the website repo. Thanks again for doing such an amazing job, I really do appreciate it!

**Comment by mutasim77** [comment]
Oh okay got it. 
Thanks also for such a library

**Comment by spleafy** [comment]
I really appreciate the fact that you like Prismane. I hope that you keep contributing, you have done a great job and I am more thank thankful for helping in growing Prismane. If you wish to contribute more, just let me know and we can get in contact.

**Pull request merged**
